name: 'tag'
on:
  pull_request:
    branches: 
      - master
      - main  
  push:
    branches: 
      - master
      - main
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
     - name: Checkout Code
       uses: actions/checkout@v2
     - name: Set Tag Output
       id: set-tag
       run:  echo "::set-output name=tag_name::$(sh version.sh)"
     - name: Create Tag
       uses: actions/github-script@v3
       env:
          TAG: ${{ steps.set-tag.outputs.tag_name }}
       with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
             ref: "refs/tags/${{ steps.set-tag.outputs.tag_name }}",
              sha: context.sha
            })
